name: GitHub Automatic Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.tag }}
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        tag:
          - "9.2.8"
          - "19.5-Matrix"
          - "20.0-Nexus_rc2"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install gcc make git unzip wget xz-utils bc gperf zip unzip g++ xsltproc xfonts-utils patchutils lzop libxml-parser-perl libparse-yapp-perl
      - name: Download the CoreELEC
        run: git clone https://github.com/CoreELEC/CoreELEC
      - name: CoreELEC release tags checkout
        run: |
          cd CoreELEC
          git checkout ${{ matrix.tag }}
      - name: Patches adding ...
        run: |
          mkdir -p ${{ github.workspace }}/CoreELEC/packages/addons/addon-depends/libdvbcsa/patches
          cp ${{ github.workspace }}/.github/patches/libdvbcsa.patch ${{ github.workspace }}/CoreELEC/packages/addons/addon-depends/libdvbcsa/patches/libdvbcsa-100-LS.patch
          cp ${{ github.workspace }}/.github/patches/tvheadend42.patch ${{ github.workspace }}/CoreELEC/packages/addons/service/tvheadend42/patches/tvheadend42-100-LS.patch
          cp ${{ github.workspace }}/.github/patches/tvheadend43.patch ${{ github.workspace }}/CoreELEC/packages/addons/service/tvheadend43/patches/tvheadend43-100-LS.patch
          if [ "${{ matrix.tag }}" != "9.2.8" ]; then
             cp ${{github.workspace}}/.github/patches/tvheadend43.patch ${{github.workspace}}/CoreELEC/projects/Amlogic-ce/packages/addons/service/tvheadend43/patches/tvheadend43-100-LS.patch
          fi
      - name: Building addons
        run: |
          if [ "${{ matrix.tag }}" == "9.2.8" ]; then
             cd ${{ github.workspace }}/CoreELEC && ARCH=arm PROJECT=Amlogic scripts/create_addon tvheadend42 tvheadend43
          else
             cd ${{ github.workspace }}/CoreELEC && ARCH=arm PROJECT=Amlogic-ce DEVICE=Amlogic-ng scripts/create_addon tvheadend42 tvheadend43
          fi
      - name: Compress addons
        run: |
          cd ${{ github.workspace }}/CoreELEC/target
          zip -rFS9 addons-${{ matrix.tag }}.zip addons
      - name: Upload target
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: ${{ github.workspace }}/CoreELEC/target/*.zip
