name: Check All Sources Availability

on:
  workflow_dispatch:

jobs:
  check-sources:
    runs-on: ubuntu-22.04
    steps:
      - name: 🔌 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📥 Clone CoreELEC
        run: git clone https://github.com/CoreELEC/CoreELEC --branch coreelec-22 --depth 1

      - name: 📌 Get build paths
        run: |
          cd CoreELEC
          ARCH=aarch64 PROJECT=Amlogic-ce DEVICE=Amlogic-no . config/options
          echo "sources_dir=${SOURCES}" >> $GITHUB_ENV

      - name: 🔍 Check all sources recursively
        run: |
          set -e
          cd CoreELEC
          ARCH=aarch64 PROJECT=Amlogic-ce DEVICE=Amlogic-no . config/options

          declare -A VISITED
          QUEUE=("packages/multimedia/ffmpeg/package.mk" "packages/addons/service/tvheadend43/package.mk")

          get_deps() {
            local pkgfile="$1"
            # Evitar duplicados
            if [[ -n "${VISITED[$pkgfile]}" ]]; then
              return
            fi
            VISITED[$pkgfile]=1

            # Cargar package.mk
            source "$pkgfile" || true

            # Añadir dependencias
            for dep in $PKG_DEPENDS_TARGET; do
              depfile=$(find packages -type f -path "*/$dep/package.mk" | head -n1 || true)
              if [[ -n "$depfile" ]]; then
                QUEUE+=("$depfile")
              fi
            done
          }

          # Construir lista completa de paquetes
          i=0
          while [[ $i -lt ${#QUEUE[@]} ]]; do
            get_deps "${QUEUE[$i]}"
            i=$((i+1))
          done

          echo "📦 Paquetes a comprobar:"
          printf '%s\n' "${!VISITED[@]}"

          MISSING=0
          for pkgfile in "${!VISITED[@]}"; do
            source "$pkgfile" || true
            URL=$(eval echo "$PKG_URL")
            FILE=$(basename "$URL")
            NAME=$(basename "$(dirname "$pkgfile")")

            # Si no hay URL, es un paquete virtual o sin fuente → lo saltamos
            if [[ -z "$URL" ]]; then
              echo "➡ $NAME → (paquete sin fuente, se omite)"
              continue
            fi

            echo "➡ $NAME → $URL"
            if curl --head --silent --fail "$URL" >/dev/null; then
              echo "   ✅ Disponible online"
            elif [[ -f "${{ github.workspace }}/sources/$FILE" ]]; then
              echo "   ✅ Encontrado en sources locales"
            else
              echo "   ❌ NO disponible → Paquete: $NAME | URL: $URL"
              MISSING=$((MISSING+1))
            fi
          done

          if [[ $MISSING -gt 0 ]]; then
            echo "❌ $MISSING paquete(s) con fuentes no disponibles"
            exit 1
          else
            echo "🎉 Todo OK: todas las fuentes están disponibles"
          fi

