name: GitHub Automatic Build

on:
  workflow_dispatch:

jobs:
  build:
    name: coreelec-22-Amlogic-no
    runs-on: ubuntu-22.04

    steps:
      - name: 🔌️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔨️ Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc g++ make git wget zip unzip xz-utils bc curl gperf zip xsltproc \
            xfonts-utils patchutils lzop libxml-parser-perl libparse-yapp-perl \
            openjdk-11-jre-headless rsync rename jq rdfind

      - name: 📥️ Clone CoreELEC
        run: git clone https://github.com/CoreELEC/CoreELEC

      - name: 📌️ Checkout 22.0-Piers_alpha1 tag
        run: |
          cd CoreELEC
          git fetch --all --tags
          git checkout tags/22.0-Piers_alpha1

      - name: ✍️ Update libdvbcsa version manually
        run: |
          sed -i 's|PKG_VERSION=".*"|PKG_VERSION="f25351d70589ec97ae6fb7590786c9aa38b999d4"|' \
            ${{ github.workspace }}/CoreELEC/packages/addons/addon-depends/libdvbcsa/package.mk
          sed -i 's|PKG_SHA256=".*"|PKG_SHA256="807998d0cf33fea4b716f534b9658aa02b185f50e5b143620d58f520b34ce0b7"|' \
            ${{ github.workspace }}/CoreELEC/packages/addons/addon-depends/libdvbcsa/package.mk

      - name: 🧼 Reemplazar package.mk de comskip por versión estable
        run: |
          cat > ${{ github.workspace }}/CoreELEC/packages/addons/addon-depends/comskip/package.mk <<'EOF'
          # SPDX-License-Identifier: GPL-2.0-only
          # Copyright (C) 2017-present Team LibreELEC (https://libreelec.tv)

          PKG_NAME="comskip"
          PKG_VERSION="6e66de54358498aa276d233f5b3e7fa673526af1"
          PKG_SHA256="412f0cc543cbe327b36b0354c00ace260c996e95dd95cb585ca58dd52c926607"
          PKG_LICENSE="GPL"
          PKG_SITE="http://www.kaashoek.com/comskip/"
          PKG_URL="https://github.com/erikkaashoek/Comskip/archive/${PKG_VERSION}.tar.gz"
          PKG_DEPENDS_TARGET="toolchain argtable2 ffmpegx"
          PKG_DEPENDS_CONFIG="argtable2 ffmpegx"
          PKG_LONGDESC="Comskip detects commercial breaks from a video stream. It can be used for post-processing recordings."
          PKG_TOOLCHAIN="autotools"
          PKG_BUILD_FLAGS="-sysroot"

          pre_configure_target() {
            # pass ffmpegx to build
            CFLAGS+=" -I$(get_install_dir ffmpegx)/usr/local/include"
            LDFLAGS+=" -L$(get_install_dir ffmpegx)/usr/local/lib -ldl"
          }
          EOF

      - name: 🔍️ Get build paths
        run: |
          cd ${{ github.workspace }}/CoreELEC
          ARCH=aarch64 PROJECT=Amlogic-ce DEVICE=Amlogic-no . config/options
          echo "sources_dir=${SOURCES}" >> $GITHUB_ENV
          echo "build_dir=${BUILD}" >> $GITHUB_ENV
          echo "project=${DISTRONAME}-${OS_VERSION}" >> $GITHUB_ENV

      - name: 💽️ Cache build sources
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.sources_dir }}
            ${{ env.build_dir }}/.ccache
            ${{ env.build_dir }}/.ccache-local
          key: ${{ env.project }}-Amlogic-no
          restore-keys: ${{ env.project }}-

      - name: 🤔️ Link sources if needed
        run: |
          if [ -d ${{ github.workspace }}/sources ] && [ ! -d ${{ env.sources_dir }} ]; then
            ln -s ${{ github.workspace }}/sources ${{ env.sources_dir }}
          fi

      - name: 🧱 Ensure patch directories exist
        run: |
          mkdir -p ${{ github.workspace }}/CoreELEC/packages/addons/service/tvheadend42/patches
          mkdir -p ${{ github.workspace }}/CoreELEC/packages/addons/service/tvheadend43/patches

      - name: 😮️ Add patches to tvheadend addons
        run: |
          cp ${{ github.workspace }}/patches/tvheadend42.patch \
             ${{ github.workspace }}/CoreELEC/packages/addons/service/tvheadend42/patches/tvheadend42-100-LS.patch
          cp ${{ github.workspace }}/patches/tvheadend43-newer.patch \
             ${{ github.workspace }}/CoreELEC/packages/addons/service/tvheadend43/patches/tvheadend43-100-LS.patch

      - name: 🔍️ Show available addons
        run: |
          cd ${{ github.workspace }}/CoreELEC
          ./scripts/create_addon --show-only all

      - name: 👷️ Build tvheadend addons
        run: |
          cd ${{ github.workspace }}/CoreELEC
          ARCH=aarch64 PROJECT=Amlogic-ce DEVICE=Amlogic-no scripts/create_addon tvheadend42 tvheadend43

      - name: 🗜️ Compress built addons
        run: |
          cd ${{ github.workspace }}/CoreELEC/target
          zip -rFS9 addons-Amlogic-no.zip addons

      - name: 📤️ Upload compressed addons
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: ${{ github.workspace }}/CoreELEC/target/*.zip

      - name: 📄 Upload build logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ${{ env.build_dir }}/.threads/logs/
          if-no-files-found: warn
